### ISSUE TITLE
Tanks boiloff even when electricity need is completely satiated, only at over x1000

### ISSUE THREAD

**Issue by rp1-lox** [post-kerbin-mining-corporation/CryoTanks#126]
During a session, I noticed that tanks would boil off at over 1000x warp. At 1000x , they would work just fine. Any faster, however, and the tanks would begin to boil off. I switched on infinite electricity, and the game demonstrated the same problem. 
KSP.log attached
[KSP.log](https://github.com/post-kerbin-mining-corporation/CryoTanks/files/7447998/KSP.log)
:

**Comment by ChrisAdderley** [comment]
Please provide more information, such as a reproducible test case (steps to reproduce the issue with a minimum mod list) and a mod list (specifically with versions of CryoTanks and Dynamic Battery Storage).

**Comment by endrjux** [comment]
Hello,

I think I observe somewhat similar behavior - in **max** warp, electricity is being depleted even though it should not be. While this is reported in this repo, I think this is rather Dynamic Battery Storage issue.

I removed all irrelevant mods (ie. I left only cryo mods and their dependencies) and started a new sandbox game. I built a test rocket, with LH2 tanks (cooling on, both stock tank and cryo tank to see if the behave differently), probe core, batteries, solar panels and some lights. I put that vessel in 86 km orbit using debug menu.

![obraz](https://github.com/post-kerbin-mining-corporation/CryoTanks/assets/688476/389e58e4-230e-4b22-b59e-d41e27c8ba3a)

2k EC storage should last for about 50 minutes and dark time is around 11 minutes, so the vehicle shouldn't ever run out of power and LH2 shouldn't boil off. Everything works as expected up to max warp speed. I wanted to test if this is something specific to cryo tanks, so I disabled cooling and only kept lights on. The same thing happened - in max warp EC goes to 0 and lights turn off. Later, when lights are off and the only drain comes from the probe core (and reaction wheel?), everything _seems_ to be fine (though it's somewhat difficult to tell if the problem is still there, I guess it is, just harder to notice).

Log:  [cryo_power_issue.log](https://github.com/post-kerbin-mining-corporation/CryoTanks/files/12268261/cryo_power_issue.log) (I enabled debug in Dynamic Battery Storage)
Craft: [Cryo EC test.craft.txt](https://github.com/post-kerbin-mining-corporation/CryoTanks/files/12268263/Cryo.EC.test.craft.txt) (github doesn't like `.craft` extension)

I also tested a minimal rocket - tanks, probe, batteries, panels. It behaves the same. Dynamic Battery Storage doesn't seem to take reaction wheel into consideration, but EC goes to 0 and LH2 boils off even without it, so I think this is unrelated. I also checked if it matters if cooling is on/off on stock or cryo tank and it doesn't. In the end I think this is not related to any part - it's most likely Dynamic Battery Storage issue. (Actually it's a KSP issue because EC should be properly calculated in the first place...)

**Comment by ChrisAdderley** [comment]
I tracked a possible issue into solar panel frame inconsistency at very high timewarp, so I've added more handling to that. I'd encourage testing with CT 1.6.6 and DBS 2.3.0

**Comment by endrjux** [comment]
@ChrisAdderley sorry for late reply. Unfortunately, I think this still doesn't work correctly. Everything is fine up to 1000x warp, but boiloff starts to happen occasionally with 10000x warp, and more frequently with 100000x warp. It's now much slower than it was before (doesn't happen every orbit I guess), but still happens even though battery should survive darkness time. (Craft is: 2500 Ec battery, 2x8.3 Ec/s panels, H250-64 cryo tank with LH2/LOX, 1.6 Ec/s needed for cooling, some probe core. 86 km Kerbin orbit via cheats. According to the info panel in VAB, battery should last 25 minutes, and be fully charged in around 3 minutes, where dark time is around 11 minutes)

VAB:
![Image](https://github.com/user-attachments/assets/d784f81c-060b-42a7-b3df-08f226b5ca31)

![Image](https://github.com/user-attachments/assets/dd6d12f8-d2c5-4b8a-8bcb-952f0f3d4805)
![Image](https://github.com/user-attachments/assets/3d39126e-385f-4f30-bcba-30b9c56dcb53)

Some time later during max warp, boiloff visible, (night):
![Image](https://github.com/user-attachments/assets/32e6dab5-8e00-4343-be36-123a217a401c)
And later, day this time:
![Image](https://github.com/user-attachments/assets/cfaea901-3a1a-4af7-a203-e55198b59b5f)

(CT 1.6.6, DBS 2.3.6.0)
I guess #143 is a duplicate of this.

**Comment by ChrisAdderley** [comment]
#143 is a different issue.

What you're describing is kinda just... a KSP problem. If you're in orbits with only solar power generation at high time warps there's no guarantee that the timesteps that the game selects and does processing on are sufficient to accurately model the orbit. 

As an example, in an 80 km Kerbin orbit you're at about 22 minutes of orbit time, half of that generating power. If you are running at 10 000x, you're getting about 200 seconds per physics tick (0.02 ticks per second) - so that's only about 3 ticks in the sun and 3 in dark. At 100 000 that's even worse, each tick is 2000s, you're getting > 1 orbit per tick. You cannot easily predict where those samples are - sometimes they're in the dark, sometimes in the sun. So you get some orbits where you have a tick of power, some where you have no power and just consumption. 

There isn't an easy fix for this without rewriting the resource system (which to be honest given the number of major issues resident in this model, isn't the worst idea). Gameplay-wise, higher orbits will manage this better..

**Comment by endrjux** [comment]
Thanks for the explanation. I thought this was the problem DBS was trying to solve, but now that I think about it, even with arbitrarily large Ec buffer, if you're unlucky and the game thinks you're always in the dark, the buffer will eventually run out. The (only?) solution would be to detect when vessel is below the limit of what DBS can fix and make Ec infinite if it should "theoretically" suffice. Anyhow, I guess there are more important things than this, and boiloff can always be disabled. ;-)

**Comment by ChrisAdderley** [comment]
I had a small idea this morning: you could see if it helps mitigate things (replace dll with this one) https://github.com/post-kerbin-mining-corporation/CryoTanks/blob/dev/GameData/CryoTanks/Plugins/SimpleBoiloff.dll

**Comment by endrjux** [comment]
I used exactly the same vessel and test scenario, no boiloff whatsoever in max warp. Works great now!

**Comment by ChrisAdderley** [comment]
I implemented a tolerance. Effectively now there is a timer of physics frames when you have no power. So if you have no power for less than 30 frames you will see no boiloff. That's less than a second realtime, so shouldn't matter much at low warps, but if power is very flickery, as it would be in this case, it'll smooth things out.
