### ISSUE TITLE
Getting the previous Error of cyrotank boiloff.

### ISSUE THREAD

**Issue by xaerogonzo** [post-kerbin-mining-corporation/CryoTanks#89]
I have been getting this for a while and i noticed this was a previous problem. I get massive spam of this error. Can a game get unstabled over time? Would a reinstall help? 

NullReferenceException: Object reference not set to an instance of an object
	SimpleBoiloff.ModuleCryoTank.Update () (at <249ca1d9eb3c4f67a8d3a27f87ab9164>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by ChrisAdderley** [comment]
I need a full log, modlist, reproduction steps to help.

**Comment by ConfusedMerlin** [comment]
Hello,
I may be able to provide some information about this.

First, I had a problem with Dynamic Battery Storage that may have been caused by CKAN missing to add the (non core) Interstellar Fuel Switch Mod. This caused the came to throw endless ammounts of exceptions when trying to launch anythings. 

While this seems to be gone after adding the (non core) IFS, I noticed that no tank could carry the LH2/Ox Fuel combination any more. By accident I added one of your tanks (H125-4) which caused the VAB to do instant lagging. It was littered with this: 

[EXC 11:47:20.253] NullReferenceException: Object reference not set to an instance of an object
	SimpleBoiloff.ModuleCryoTank.Update () (at <249ca1d9eb3c4f67a8d3a27f87ab9164>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

I made you a zip containing the KSP.log and the moduleManager cache file (I heard it may contain all mods that were loaded?)

https://drive.google.com/open?id=1ymKOxl0ck7zUriVyYHTe29299TCkQrVC

*sigh* all I wanted was sending a craft to Mun containing a lh2 engine, but noooo...
